routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/admin-panal/login', 'Auth\AdminLoginController@showLoginForm')->name('admin-panal.login');
Route::post('/admin-panal/login', 'Auth\AdminLoginController@login')->name('admin-panal.login.submit');

Route::group(['middleware' => 'auth:admin'], function() 
{   
    //==================================================================================
    //dataTables routes
    //==================================================================================

    Route::get('admin-panal/users/data', 'UserController@anyData');
    Route::get('admin-panal/buildings/data', 'BuController@anyData');
    Route::get('admin-panal/contactus/data', 'ContactusController@anyData');
    
    //==================================================================================
    //admin routes
    //==================================================================================
    
    Route::post('/admin-panal/buildings/statistics/', 'AdminController@ShowStatisticsByYear');
    Route::post('admin-panal/users/PasswordChange', 'UserController@updatePassword');

    Route::get('/admin-panal', 'AdminController@index')->name('admin-panal');

    Route::get('/admin-panal/buildings/statistics', 'AdminController@ViewBuStatistics');

    Route::get('/admin-panal/profile/{admin}', 'AdminController@AdminProfile')->name('admin-profile');
    Route::patch('/admin-panal/profile/{id}', 'AdminController@update')->name('admin-panal.update');

    Route::get('/admin-panal/users/{user_id}/destroy', 'UserController@destroy');

    Route::resource('admin-panal/buildings', 'BuController', ['except' => ['index', 'show']]);
    Route::resource('/admin-panal/users', 'UserController');
    Route::resource('/admin-panal/contactus', 'ContactusController');

    Route::get('/admin-panal/contactus/{id}/destroy', 'ContactusController@destroy');
    Route::get('/admin-panal/settings', 'SettingsController@index');

    Route::get('admin-panal/buildings/{id?}', 'BuController@index');

    Route::get('/admin-panal/buildings/{id}/destroy', 'BuController@destroy');
    Route::get('/admin-panal/ChangeStatus/{id}/{status}', 'BuController@ChangeStatus');

    Route::post('/admin-panal/settings/', 'SettingsController@store');

    //==================================================================================
    //Softdeletes routes
    //==================================================================================   
    
    Route::get('/admin-panal/buildings/{id}/restore', 'BuController@restore')->name('buildings.restore');
    Route::get('/admin-panal/buildings/get/trashed', 'BuController@getTrashed')->name('buildings.trash');
    Route::get('/admin-panal/buildings/{id}/ForceDelete', 'BuController@ForceDelete')->name('buildings.forcedelete');
});

//==================================================================================
//website side routes
//==================================================================================

Route::group(['middleware' => 'web'], function() 
{
    Route::get('/home', 'HomeController@index');
    Route::get('/ajax/buildings/information/', 'HomeController@getajaxinformation')->middleware('auth');

    Route::view('/contact-us', 'pages.contact-us')->middleware('auth');
    Route::post('/contact-us', 'ContactusController@store');

    Route::view('/services', 'pages.services');
    Route::view('/about', 'pages.about');

    Route::get('/profile/{user}', 'HomeController@profile');

    Route::get('/buildings', 'BuController@buildings')->name('buildings');
    Route::get('buildings/search', 'BuController@search');
    Route::get('buildings/ForRent', 'BuController@ForRent')->middleware('auth');
    Route::get('buildings/ForBuy', 'BuController@ForBuy')->middleware('auth');
    Route::get('buildings/type/{type}', 'BuController@ShowByType')->middleware('auth');
    Route::get('buildings/build/{build_id}', 'BuController@build')->name('build')->middleware('auth');

    Route::get('/store/make/order/type/{type}/i/{id}', 'BuController@Order')->name('makeorder')->middleware('auth');
    Route::post('/store/make/order/', 'BuController@Rent')->name('rent')->middleware('auth');

    Route::view('/user/create/building', 'user.add')->middleware('auth');
    Route::post('/user/create/building', 'BuController@userStore')->middleware('auth');

    Route::get('/profile/{user}/active', 'BuController@UserActiveBuildings')->middleware('auth');
    Route::get('/profile/{user}/disactive', 'BuController@UserDisactiveBuildings')->middleware('auth');;
    Route::get('/profile/{user}/orders', 'BuController@UserOrders')->middleware('auth');;
    Route::get('/profile/{username}/edit/', 'UserController@EditUserProfile')->middleware('auth');

    Route::post('/user/ChangePassword', 'UserController@UserChangePasssword')->middleware('auth');
    Route::get('/buildings/build/{id}/edit', 'BuController@UserEditBuilding')->name('build.edit')->middleware('auth');

    Route::patch('/user/UpdateUserData/', ['as' => 'user.UpdateUserData', 'uses' => 'UserController@UpdateUserData'])->middleware('auth');
    Route::patch('/user/update/building', 'BuController@UserUpdateBuilding')->middleware('auth');
});

resources/views/admin/inc/chart.blade.php
<script type="text/javascript">

    // -----------------------
    // - MONTHLY SALES CHART -
    // -----------------------

    // Get context with jQuery - using jQuery's .get() method.
    var salesChartCanvas = $('#salesChart').get(0).getContext('2d');
    
    // This will get the first returned node in the jQuery collection.
    var salesChart  = new Chart(salesChartCanvas);

    var salesChartData = {
        labels  : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        datasets: [{
            label               : 'Digital Goods',
            fillColor           : 'rgba(60,141,188,0.9)',
            strokeColor         : 'rgba(60,141,188,0.8)',
            pointColor          : '#3b8bba',
            pointStrokeColor    : 'rgba(60,141,188,1)',
            pointHighlightFill  : '#fff',
            pointHighlightStroke: 'rgba(60,141,188,1)',
            data : [@foreach($new as $chart){{ (is_array($chart)) ? $chart['count'].',' : $chart.',' }}@endforeach]
        }]
    };

    var salesChartOptions = {

    // Boolean - If we should show the scale at all
    showScale               : true,
    
    // Boolean - Whether grid lines are shown across the chart
    scaleShowGridLines      : false,
    
    // String - Colour of the grid lines
    scaleGridLineColor      : 'rgba(0,0,0,.05)',
    
    // Number - Width of the grid lines
    scaleGridLineWidth      : 1,
    
    // Boolean - Whether to show horizontal lines (except X axis)
    scaleShowHorizontalLines: true,
    
    // Boolean - Whether to show vertical lines (except Y axis)
    scaleShowVerticalLines  : true,
    
    // Boolean - Whether the line is curved between points
    bezierCurve             : true,
    
    // Number - Tension of the bezier curve between points
    bezierCurveTension      : 0.3,
    
    // Boolean - Whether to show a dot for each point
    pointDot                : false,
    
    // Number - Radius of each point dot in pixels
    pointDotRadius          : 4,
    
    // Number - Pixel width of point dot stroke
    pointDotStrokeWidth     : 1,
    
    // Number - amount extra to add to the radius to cater for hit detection outside the drawn point
    pointHitDetectionRadius : 20,
    
    // Boolean - Whether to show a stroke for datasets
    datasetStroke           : true,
    
    // Number - Pixel width of dataset stroke
    datasetStrokeWidth      : 2,
    
    // Boolean - Whether to fill the dataset with a color
    datasetFill             : true,
    
    // String - A legend template
    legendTemplate          : '<ul class=\'<%=name.toLowerCase()%>-legend\'><% for (var i=0; i<datasets.length; i++){%><li><span style=\'background-color:<%=datasets[i].lineColor%>\'></span><%=datasets[i].label%></li><%}%></ul>',
    
    // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
    maintainAspectRatio     : true,
    
    // Boolean - whether to make the chart responsive to window resizing
    responsive              : true
  };
</script>

resources/views/admin/inc/footer.blade.php
		<footer class="main-footer">
			<div class="pull-right hidden-xs">
				<b>Version</b> 2.4.0
			</div>
			<strong>Copyright &copy; 2014-{{ date('Y') }} <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
			reserved.
		</footer>

		<!-- Control Sidebar -->
		<aside class="control-sidebar control-sidebar-dark">
			<!-- Create the tabs -->
			<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
				<li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
				<li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
			</ul>
			<!-- Tab panes -->
			<div class="tab-content">
				<!-- Home tab content -->
				<div class="tab-pane" id="control-sidebar-home-tab">
					<h3 class="control-sidebar-heading">Recent Activity</h3>
					<ul class="control-sidebar-menu">
						<li>
							<a href="javascript:void(0)">
								<i class="menu-icon fa fa-birthday-cake bg-red"></i>

								<div class="menu-info">
									<h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

									<p>Will be 23 on April 24th</p>
								</div>
							</a>
						</li>
						<li>
							<a href="javascript:void(0)">
								<i class="menu-icon fa fa-user bg-yellow"></i>

								<div class="menu-info">
									<h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

									<p>New phone +1(800)555-1234</p>
								</div>
							</a>
						</li>
						<li>
							<a href="javascript:void(0)">
								<i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

								<div class="menu-info">
									<h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

									<p>nora@example.com</p>
								</div>
							</a>
						</li>
						<li>
							<a href="javascript:void(0)">
								<i class="menu-icon fa fa-file-code-o bg-green"></i>

								<div class="menu-info">
									<h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

									<p>Execution time 5 seconds</p>
								</div>
							</a>
						</li>
					</ul>
					<!-- /.control-sidebar-menu -->

					<h3 class="control-sidebar-heading">Tasks Progress</h3>
					<ul class="control-sidebar-menu">
						<li>
							<a href="javascript:void(0)">
								<h4 class="control-sidebar-subheading">
									Custom Template Design
									<span class="label label-danger pull-right">70%</span>
								</h4>

								<div class="progress progress-xxs">
									<div class="progress-bar progress-bar-danger" style="width: 70%"></div>
								</div>
							</a>
						</li>
						<li>
							<a href="javascript:void(0)">
								<h4 class="control-sidebar-subheading">
									Update Resume
									<span class="label label-success pull-right">95%</span>
								</h4>

								<div class="progress progress-xxs">
									<div class="progress-bar progress-bar-success" style="width: 95%"></div>
								</div>
							</a>
						</li>
						<li>
							<a href="javascript:void(0)">
								<h4 class="control-sidebar-subheading">
									Laravel Integration
									<span class="label label-warning pull-right">50%</span>
								</h4>

								<div class="progress progress-xxs">
									<div class="progress-bar progress-bar-warning" style="width: 50%"></div>
								</div>
							</a>
						</li>
						<li>
							<a href="javascript:void(0)">
								<h4 class="control-sidebar-subheading">
									Back End Framework
									<span class="label label-primary pull-right">68%</span>
								</h4>

								<div class="progress progress-xxs">
									<div class="progress-bar progress-bar-primary" style="width: 68%"></div>
								</div>
							</a>
						</li>
					</ul>
					<!-- /.control-sidebar-menu -->

				</div>
				<!-- /.tab-pane -->
				<!-- Stats tab content -->
				<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
				<!-- /.tab-pane -->
				<!-- Settings tab content -->
				<div class="tab-pane" id="control-sidebar-settings-tab">
					<form method="post">
						<h3 class="control-sidebar-heading">General Settings</h3>

						<div class="form-group">
							<label class="control-sidebar-subheading">
								Report panel usage
								<input type="checkbox" class="pull-right" checked>
							</label>

							<p>
								Some information about this general settings option
							</p>
						</div>
						<!-- /.form-group -->

						<div class="form-group">
							<label class="control-sidebar-subheading">
								Allow mail redirect
								<input type="checkbox" class="pull-right" checked>
							</label>

							<p>
								Other sets of options are available
							</p>
						</div>
						<!-- /.form-group -->

						<div class="form-group">
							<label class="control-sidebar-subheading">
								Expose author name in posts
								<input type="checkbox" class="pull-right" checked>
							</label>

							<p>
								Allow the user to show his name in blog posts
							</p>
						</div>
						<!-- /.form-group -->

						<h3 class="control-sidebar-heading">Chat Settings</h3>

						<div class="form-group">
							<label class="control-sidebar-subheading">
								Show me as online
								<input type="checkbox" class="pull-right" checked>
							</label>
						</div>
						<!-- /.form-group -->

						<div class="form-group">
							<label class="control-sidebar-subheading">
								Turn off notifications
								<input type="checkbox" class="pull-right">
							</label>
						</div>
						<!-- /.form-group -->

						<div class="form-group">
							<label class="control-sidebar-subheading">
								Delete chat history
								<a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
							</label>
						</div>
						<!-- /.form-group -->
					</form>
				</div>
				<!-- /.tab-pane -->
			</div>
		</aside>

		<div class="control-sidebar-bg"></div>

resources/views/admin/inc/header.blade.php
@php
	$admin_image = SetImage($auth->user_image, 'users');
@endphp
<header class="main-header">
	
	<a href="{{ route('admin-panal') }}" class="logo">
		<span class="logo-mini"><b>A</b>DP</span>
		<span class="logo-lg"><b>Admin </b>Panal</span>
	</a>
	
	<nav class="navbar navbar-static-top">
		
		<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>
		
		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">
				
				<li class="dropdown messages-menu">
					
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-envelope-o"></i>
						@if(getUnreadedMessagesCount() != 0)
							<span class="label label-success">{{ getUnreadedMessagesCount() }}</span>
						@else
							<span></span>
						@endif
					</a>
					
					<ul class="dropdown-menu">
						<li class="header">
							You have {{ getUnreadedMessagesCount() == 0 ? 'No Messages' : getUnreadedMessagesCount().' unreaded' }}
						</li>
						<li>
							<ul class="menu">
								@forelse(getUnreadedMessages() as $key => $value)
								@php
									$img = GetImage($value->image, '/public/one/uploads/users/', '/one/uploads/users/');
								@endphp
								<li>
									<a href="{{ url('admin-panal/contactus/'.$value->id.'/edit') }}">
										<div class="pull-left">
											<img src="{{ $img }}" class="img-circle" alt="User Image">
										</div>
										<h4>{{ ucfirst($value->co_name) }}<small><i class="fa fa-clock-o"></i> {{ $value->created_at->diffForHumans() }}</small></h4>
										<p><span><i class="label label-info"></i> Subject : {{ $value->co_subject }}</span><br>{{ str_limit($value->co_message, 20) }}</p>
									</a>
								</li>
								@empty
									<li class="text-center" style="padding:10px;">{{ __('NO Messages') }}</li>
								@endforelse
							</ul>
						</li>
						<li class="footer"><a href="{{ url('admin-panal/contactus') }}">See All Messages</a></li>
					</ul>
				</li>
				
				<li class="dropdown notifications-menu">
					
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-bell-o"></i>
						<span class="label label-warning">{{ getBuildingsStatusCount('Disactive') }}</span>
					</a>
 
					<ul class="dropdown-menu">
						<li class="header">
							You have {{ getBuildingsStatusCount('Disactive') }} notifications
						</li>
						<li>
							<ul class="menu">
								@forelse(App\Buliding::where('bu_status', 'Disactive')->get() as $dis)
										<li>
											<div class="pull-left">
												<i class="fa fa-users text-red"></i>
												<a class="btn btn-default text-center" href="{{ url('/admin-panal/buildings/'.$dis->id.'/edit') }}">{{ $dis->bu_name }}</a>
											</div>
											<a class="pull-right btn text-center" href="{{ url('/admin-panal/ChangeStatus/'.$dis->id.'/Active') }}">Set Active</a>
											<div class="clearfix"></div>
										</li>
								@empty
									<li>{{ __('No Disactive Buildings Avilable Right Now !!') }}</li>
								@endforelse
							</ul>
						</li>
						<li class="footer"><a href="#">View all</a></li>
					</ul>
				</li>
				
				<li class="dropdown user user-menu">
					
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<img src="{{ $admin_image }}"  class="user-image" alt="IMG">
						<span class="hidden-xs">{{ $auth->name }}</span>
					</a>
					
					<ul class="dropdown-menu">
						
						<li class="user-header">
							<img src="{{ $admin_image }}" class="img-circle" alt="User Image">
							<p>{{ $auth->name }} - Web Developer<small>Member since Nov. {{ $auth->created_at->year }}</small></p>
						</li>
						
						<li class="user-body">
							<div class="row">
								<div class="col-xs-4 text-center"><a href="#">Followers</a></div>
								<div class="col-xs-4 text-center"><a href="#">Sales</a></div>
								<div class="col-xs-4 text-center"><a href="#">Friends</a></div>
							</div>
						</li>
						
						<li class="user-footer">
							
							<div class="pull-left">
								<a href="{{ url('/admin-panal/profile/'.$auth->name) }}" class="btn btn-default btn-flat">Profile</a>
							</div>
							
							<div class="pull-right">
								<a class="btn btn-default btn-flat" href="{{ route('logout') }}"
	                               onclick="event.preventDefault();document.getElementById('logout-form').submit();">
	                               {{ __('Sign out') }}
	                            </a>
	                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
									@csrf
                            	</form>
	                        </div>
						</li>

					</ul>
				</li>
				
				<li><a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a></li>
			</ul>
		</div>
	</nav>
</header>

resources/views/admin/inc/map.blade.php
<script type="text/javascript">

	/* 
	** jVector Maps
   	** Create a world map with markers
   	**/

   	$('#world-map-markers').vectorMap({
   		map              : 'world_mill_en',
	    normalizeFunction: 'polynomial',
	    hoverOpacity     : 0.7,
	    hoverColor       : true,
	    backgroundColor  : 'transparent',
	    regionStyle      : {
	    	initial      : {
	    		fill            : 'rgba(210, 214, 222, 1)', 'fill-opacity'  : 1,
	    		stroke          : 'none', 'stroke-width'  : 0, 'stroke-opacity': 1
	    	},
	    	hover        : {
	    		'fill-opacity': 0.7,
	    		cursor        : 'pointer'
	    	},
	    	selected     : {
	    		fill: 'yellow'
	    	},
	    	selectedHover: {}
	    },
	    markerStyle      : {
	    	initial: {
	    		fill  : '#00a65a',
	    		stroke: '#111'
	    	}
	    },
	    markers          : [
	    	@foreach($maps as $map)
	    		{ latLng: [{{ $map->bu_latitude }}, {{ $map->bu_langtude }}], name: '{{ $map->bu_name }}' },
    		@endforeach
    	]
  	});
</script>

resources/views/admin/inc/scripts.blade.php
  	<!-- jQuery 3 -->
    {{ Html::script('admin/bower_components/jquery/dist/jquery.min.js') }}
  	
    <!-- jQuery UI 1.11.4 -->
  	{{ Html::script('admin/bower_components/jquery-ui/jquery-ui.min.js') }}
  	
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  	<script>
  		$.widget.bridge('uibutton', $.ui.button);
  	</script>
  	
		<!-- Bootstrap 3.3.7 -->

  	{{ Html::script('admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}
  	
    <!-- Morris.js charts -->
  	{{ Html::script('admin/bower_components/raphael/raphael.min.js') }}
  	{{ Html::script('admin/bower_components/morris.js/morris.min.js') }}
  	
    <!-- Sparkline -->
  	{{ Html::script('admin/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}
  	
    <!-- jvectormap -->
  	{{ Html::script('admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}
  	{{ Html::script('admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}
  	
    <!-- jQuery Knob Chart -->
  	{{ Html::script('admin/bower_components/jquery-knob/dist/jquery.knob.min.js') }}
  	
    <!-- daterangepicker -->
  	{{ Html::script('admin/bower_components/moment/min/moment.min.js') }}
  	{{ Html::script('admin/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}
  	
    <!-- datepicker -->
  	{{ Html::script('admin/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}
  	
    <!-- Bootstrap WYSIHTML5 -->
  	{{ Html::script('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}
  	
    <!-- Slimscroll -->
  	{{ Html::script('admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}
  	
    <!-- FastClick -->
  	{{ Html::script('admin/bower_components/fastclick/lib/fastclick.js') }}
  	
    <!-- AdminLTE App -->
  	{{ Html::script('admin/dist/js/adminlte.min.js') }}
  	
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  	{{ Html::script('admin/dist/js/pages/dashboard.js') }}

    {{-- dashboard 2 --}}
    {{ Html::script('admin/dist/js/pages/dashboard2.js') }}

    <!-- SlimScroll -->
    {{ Html::script('admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}
    <!-- ChartJS -->
    {{ Html::script('admin/bower_components/chart.js/Chart.js') }}  	
    <!-- AdminLTE for demo purposes -->
  	{{ Html::script('admin/dist/js/demo.js') }}
		{{ Html::script('admin/cus/sweetalert2.all.js') }}
    {{ Html::script('admin/dist/js/select2.min.js') }}
    <script type="text/javascript">
        $('.select2').select2();
    </script>

resources/views/admin/inc/sidebar.blade.php
<aside class="main-sidebar">

	<section class="sidebar">
		<div class="user-panel">
			<div class="pull-left image">
				<img src="{{ GetImage($auth->user_image, '/public/one/uploads/users/', '/one/uploads/users/') }}" class="img-circle" alt="User Image">
			</div>
			<div class="pull-left info">
				<p>{{ $auth->name }}</p>
				<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>

		<form action="#" method="get" class="sidebar-form">
			<div class="input-group">
				<input type="text" name="q" class="form-control" placeholder="Search...">
				<span class="input-group-btn">
					<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
					</button>
				</span>
			</div>
		</form>

		<ul class="sidebar-menu" data-widget="tree">
			<li class="header">MAIN NAVIGATION</li>
			
			<li><a href="{{ url($root.'/admin-panal/') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
			
			<li class="treeview">
				<a href="#">
					<i class="fa fa-users"></i> <span>Users</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li><a href="/admin-panal/users/create"><i class="fa fa-circle-o"></i>Add New User</a></li>
					<li><a href="/admin-panal/users"><i class="fa fa-circle-o"></i> Display All Users</a></li>
				</ul>
			</li>

			<li class="treeview">
				<a href="#">
					<i class="fa fa-address-book"></i> <span>Contacts</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li><a href="/admin-panal/contactus"><i class="fa fa-circle-o"></i> Display All Contacts</a></li>
				</ul>
			</li>
			
			<li class="treeview">
				<a href="#">
					<i class="fa fa-university" aria-hidden="true"></i> <span>Buildings</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('buildings.create') }}"><i class="fa fa-circle-o"></i>Add New Building</a></li>
					<li><a href="/admin-panal/buildings"><i class="fa fa-circle-o"></i> Display All Buildings</a></li>
					<li><a href="{{ route('buildings.trash') }}"><i class="fa fa-circle-o"></i> Deleted Buildings</a></li>
				</ul>
			</li>
			
			<li><a href="{{ url('/admin-panal/settings/') }}"><i class="fa fa-gear"></i> <span>Settings</span></a></li>
			<li><a href="{{ url($root) }}" target="_blanck"><i class="fa fa-bug"></i> <span>Website</span></a></li>
			<li><a href="{{ url($root.'/admin-panal/buildings/statistics') }}"><i class="fa fa-bar-chart"></i> <span>Statistics</span></a></li>
		</ul>
	</section>
</aside>