routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/admin-panal/login', 'Auth\AdminLoginController@showLoginForm')->name('admin-panal.login');
Route::post('/admin-panal/login', 'Auth\AdminLoginController@login')->name('admin-panal.login.submit');

Route::group(['middleware' => 'auth:admin'], function() 
{   
    //==================================================================================
    //dataTables routes
    //==================================================================================

    Route::get('admin-panal/users/data', 'UserController@anyData');
    Route::get('admin-panal/buildings/data', 'BuController@anyData');
    Route::get('admin-panal/contactus/data', 'ContactusController@anyData');
    
    //==================================================================================
    //admin routes
    //==================================================================================
    
    Route::post('/admin-panal/buildings/statistics/', 'AdminController@ShowStatisticsByYear');
    Route::post('admin-panal/users/PasswordChange', 'UserController@updatePassword');

    Route::get('/admin-panal', 'AdminController@index')->name('admin-panal');

    Route::get('/admin-panal/buildings/statistics', 'AdminController@ViewBuStatistics');

    Route::get('/admin-panal/profile/{admin}', 'AdminController@AdminProfile')->name('admin-profile');
    Route::patch('/admin-panal/profile/{id}', 'AdminController@update')->name('admin-panal.update');

    Route::get('/admin-panal/users/{user_id}/destroy', 'UserController@destroy');

    Route::resource('admin-panal/buildings', 'BuController', ['except' => ['index', 'show']]);
    Route::resource('/admin-panal/users', 'UserController');
    Route::resource('/admin-panal/contactus', 'ContactusController');

    Route::get('/admin-panal/contactus/{id}/destroy', 'ContactusController@destroy');
    Route::get('/admin-panal/settings', 'SettingsController@index');

    Route::get('admin-panal/buildings/{id?}', 'BuController@index');

    Route::get('/admin-panal/buildings/{id}/destroy', 'BuController@destroy');
    Route::get('/admin-panal/ChangeStatus/{id}/{status}', 'BuController@ChangeStatus');

    Route::post('/admin-panal/settings/', 'SettingsController@store');

    //==================================================================================
    //Softdeletes routes
    //==================================================================================   
    
    Route::get('/admin-panal/buildings/{id}/restore', 'BuController@restore')->name('buildings.restore');
    Route::get('/admin-panal/buildings/get/trashed', 'BuController@getTrashed')->name('buildings.trash');
    Route::get('/admin-panal/buildings/{id}/ForceDelete', 'BuController@ForceDelete')->name('buildings.forcedelete');
});

//==================================================================================
//website side routes
//==================================================================================

Route::group(['middleware' => 'web'], function() 
{
    Route::get('/home', 'HomeController@index');
    Route::get('/ajax/buildings/information/', 'HomeController@getajaxinformation')->middleware('auth');

    Route::view('/contact-us', 'pages.contact-us')->middleware('auth');
    Route::post('/contact-us', 'ContactusController@store');

    Route::view('/services', 'pages.services');
    Route::view('/about', 'pages.about');

    Route::get('/profile/{user}', 'HomeController@profile');

    Route::get('/buildings', 'BuController@buildings')->name('buildings');
    Route::get('buildings/search', 'BuController@search');
    Route::get('buildings/ForRent', 'BuController@ForRent')->middleware('auth');
    Route::get('buildings/ForBuy', 'BuController@ForBuy')->middleware('auth');
    Route::get('buildings/type/{type}', 'BuController@ShowByType')->middleware('auth');
    Route::get('buildings/build/{build_id}', 'BuController@build')->name('build')->middleware('auth');

    Route::get('/store/make/order/type/{type}/i/{id}', 'BuController@Order')->name('makeorder')->middleware('auth');
    Route::post('/store/make/order/', 'BuController@Rent')->name('rent')->middleware('auth');

    Route::view('/user/create/building', 'user.add')->middleware('auth');
    Route::post('/user/create/building', 'BuController@userStore')->middleware('auth');

    Route::get('/profile/{user}/active', 'BuController@UserActiveBuildings')->middleware('auth');
    Route::get('/profile/{user}/disactive', 'BuController@UserDisactiveBuildings')->middleware('auth');;
    Route::get('/profile/{user}/orders', 'BuController@UserOrders')->middleware('auth');;
    Route::get('/profile/{username}/edit/', 'UserController@EditUserProfile')->middleware('auth');

    Route::post('/user/ChangePassword', 'UserController@UserChangePasssword')->middleware('auth');
    Route::get('/buildings/build/{id}/edit', 'BuController@UserEditBuilding')->name('build.edit')->middleware('auth');

    Route::patch('/user/UpdateUserData/', ['as' => 'user.UpdateUserData', 'uses' => 'UserController@UpdateUserData'])->middleware('auth');
    Route::patch('/user/update/building', 'BuController@UserUpdateBuilding')->middleware('auth');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;


class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password', 'username', 'dob', 'user_image','location'
    ];

    protected $dates = [
        'dob'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }
    
    public function getNameAttribute()
    {
        return ucfirst($this->attributes['name']);
    }

    public function user_bu(){ $this->belongsToMany(Buliding::class)->withTimestamps(); }

    public function Orders()
    {
        $this->hasMany(Order::class);
    }
    //SELECT count(*) as count, user_id as user FROM `bulidings` GROUP BY(user_id)
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests\AddUsersAdminRequest;
use App\Http\Requests\PasswordChangeRequest;
use App\Http\Requests\EditUserRequest;
use Redirect;
use Hash;
use App\User;
use App\Buliding;
use DataTables;
use Auth;

class UserController extends Controller
{
    public function index()
    {
        return view('admin.users.index');
    }

    public function create()
    {
        return view('admin.users.add');
    }
    public function show()
    {
        //
    }
    public function store(AddUsersAdminRequest $request)
    {
        if($request->file('user_image')){
            
            $filename = uploadimage($request->file('user_image', '/public/one/uploads/users/'));
            
            if(!$filename){return back()->withFlashMessage('Please Choose another image that has a size (750x750) !!');}
            
            $image = $filename;

        }else $image = '';
        
        User::create([
            'name'       => $request->name,
            'username'   => $request->username,
            'email'      => $request->email,
            'password'   => $request->password,
            'location'   => $request->location,
            'dob'        => $request->dob,
            'user_image' => $image,
        ]);
        return redirect('/admin-panal/users')->withFlashMessage('Done Operation !!');
    }

    public function edit($id)
    {
        $user = User::find($id);
        
        $buActive = getUserBu($user->id, 'Active');
        $buDisactive = getUserBu($user->id, 'Disactive');
        
        return view('admin.users.edit', compact('user', 'buActive', 'buDisactive'));
    }

    public function update(EditUserRequest $request, $id)
    {
        $user = User::find($id);
        SetUploadedFile($request, $user);
        return back()->withFlashMessage('Done Operation !!');
    }

    public function destroy($user_id)
    {
        User::destroy($user_id);
        return redirect()->route('users.index')->withFlashMessage('Done Operation!');
    }

    public function updatePassword(Request $request)
    {
        Admin::find($request->id)->update(['password' => $request->password]);
        return redirect()->route('users.index')->withFlashMesssage('Password has been changed successfully');
    }

    public function anyData()
    {
        $users = User::all();
        return DataTables::of($users)

            ->editColumn('name', function ($users) {
                return \Html::link('/admin-panal/users/' . $users->id . '/edit', ucfirst($users->name));
            })

            ->editColumn('mybus', function($users){
                return \Html::link('/admin-panal/buildings/' . $users->id . '/', " ", ['class' => 'btn btn-danger delete glyphicon glyphicon-user']);
            })

            ->editColumn('dob', function ($users) {
                return $users->dob->format('Y-m-d');
            })

            ->editColumn('email', function ($users) {
                $str = substr($users->email, 0, 20);
                return strlen($str) < 20 ? $str : $str . '...';
            })

            ->editColumn('age', function ($users) {
                return $users->dob->age;
            })

            ->editColumn('user_image', function($users){

                $image = ($users->user_image == '') ? 'one/uploads/no_image.jpg' : 'one/uploads/users/' . $users->user_image;

                return \Html::image($image, null, ['class'=>'img-responsive', 'width'=>'50', 'height'=>'50']); 
            })
            ->addColumn('delete', function ($users) {
                return \Html::link('/admin-panal/users/' . $users->id . '/destroy', " ", ['class' => 'btn btn-danger delete glyphicon glyphicon-remove', 'title' => 'Delete']);
            })
            ->addColumn('edit', function ($users) {
                return \Html::link('/admin-panal/users/' . $users->id . '/edit', " ", ['class' => 'btn btn-info glyphicon glyphicon-edit', 'title' => 'Edit']);
            })->make(true);
    }
    public function EditUserProfile()
    {
        $user = Auth::user();
        return view('user.edit', compact('user'));
    }

    public function UpdateUserData(EditUserRequest $request)
    {
        $auth = Auth::user();
        SetUploadedFile($request, $auth);
        return redirect()->back()->withFlashMessage('You have edit the information successfully !!');
    }
    public function UserChangePasssword(PasswordChangeRequest $request)
    {
        $auth = Auth::user();
        $id = $auth->id;
        if(Hash::check($request->password, $auth->password)){
            User::find($id)->update(['password' => $request->newpassword]);
            return back()->withFlashMessage('You have Changed the Password Successfully !!');   
        }else{
            return back()->withFlashMessage('Sorry, the password you have entered is not matched with we have !!');
        }
    }
}

resources/views/admin/users/add.blade.php
@extends('admin.layout.master')

@section('title', 'Users')

@section('content')
<div class="container">
    <div class="row">
        
        <section class="content-header" dir="rtl">
            <h1 class="pull-left" dir="ltr">Data Tables<small>advanced tables</small></h1>
            <ol class="breadcrumb">
                <li><a href="{{ $root }}/admin-panal/"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{ route('users.index') }}"><i class="fa fa-user"></i>Users</a></li>
                <li class="active"><a href="{{ route('users.create') }}"><i class="fa fa-user"></i> Add New User</a></li>
            </ol>
        </section>

        <br><br>
        
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Create a new user</div>
                <div class="panel-body">
                    {!! Form::open(['route' => 'users.index', 'method' => 'POST', 'files'=>true]) !!}
                        @include('admin.users.form')
                    
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button style="width:120px;" type="submit" name="submit" class="btn btn-lg btn-primary">{{ __('Register') }}</button>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layout.master') 

@section('title', 'Users')

@section('content')

<section class="content-header" dir="rtl">
    <h1 class="pull-left hidden-xs" dir="ltr">Users<small>Edit</small></h1>
    <ol class="breadcrumb">
        <li class="h4"><a href="{{ route('admin-panal') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="h4"><a href="{{ route('users.index') }}"><i class="fa fa-users"></i> Users</a></li>
        <li class="active h4">
            <a href="{{ route('users.edit', $user->id) }}"><i class="fa fa-edit"></i> Edit User {{ $user->name }}</a>
        </li>
    </ol>
</section>

<br class="hidden-xs"><br class="hidden-xs"><br>

<section class="content">
    <div class="row">
        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">Edit {{ $user->name }}'s Information</div>
                <div class="panel-body">
                    {!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'PATCH', 'files' => true]) !!}

                    @include('admin.users.form')
                
                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" style="width:150px;" class="btn btn-success btn-lg">
                                <i class="fa fa-edit"></i>Edit
                            </button>
                        </div>
                    </div>
                    
                    {!! Form::close() !!}
                </div>
            </div>

            {{--  Password Form  --}}
        
            <div class="panel panel-default">
                <div class="panel-heading"><h3>{{ __('Change User Password') }}</h3></div>
                <div class="panel-body">
                    {!! Form::open(['url'=>'admin-panal/users/PasswordChange', 'method'=>'POST']) !!}
                    <div class="form-group row">
                        <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>
                        <div class="col-md-6">
                            <input type="hidden" value="{{ $user->id }}" name="user_id">
                            <input 
                                id="password" 
                                type="password" 
                                class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" 
                                name="password"
                                required>
                                @if ($errors->has('password'))
                                <span class="invalid-feedback">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span> 
                                @endif
                        </div>
                    </div>
                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" style="width:150px;" class="btn btn-success btn-lg"><i class="fa fa-edit"></i>{{ __('Change') }}</button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>

        <div class="col-md-7">
            <div class="panel panel-default">
            <div class="panel-heading">User Buildings</div>
                <div class="panel-body">
                    <div class="nav-tabs-custom">
                    
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#activity" data-toggle="tab">Active Buildings</a></li>
                            <li><a href="#timeline" data-toggle="tab">Disactive Buildings</a></li>
                        </ul>

                        <div class="tab-content">
                            <div class="active tab-pane" id="activity">
                                <table class="table table-hover text-center table-bordered">
                                    <tr>
                                        <th>Building Name</th><th>Type</th><th>Price</th>
                                        <th>Square</th><th>Location</th><th>Created at</th><th>Set Disactive</th>
                                    </tr>
                                    @forelse($buActive as $active)
                                    <tr>
                                        <td><a href="{{ route('buildings.edit', $active->id) }}">{{ ucwords($active->bu_name) }}</a></td>
                                        <td>{{ $active->bu_type }}</td>
                                        <td>{{ GetMoney($active->bu_price) }}</td>
                                        <td>{{ $active->bu_square }} M</td>
                                        <td>{{ $active->bu_gov }}</td>
                                        <td>{{ $active->created_at }}</td>    
                                        <td>
                                            <a href="{{ url('/admin-panal/ChangeStatus/'.$active->id.'/Disactive') }}">
                                                <i class="fa fa-check fa-2x"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    @empty
                                        <tr><td colspan="7">{{ __('No Buildings avilable for this user') }}</td></tr>
                                    @endforelse
                                </table>
                                {{ GetPaginate($buActive) }}
                            </div>

                            <div class="tab-pane" id="timeline">
                                <table class="table table-hover text-center table-bordered">
                                    <tr>
                                        <th>Building Name</th><th>Type</th><th>Price</th>
                                        <th>Square</th><th>Location</th><th>Created at</th><th>Set Disactive</th>
                                    </tr>
                                    @forelse($buDisactive as $disactive)
                                    <tr>
                                        <td>
                                            <a href="{{ route('buildings.edit', $disactive->id) }}">{{ ucwords($disactive->bu_name) }}</a>
                                        </td>
                                        <td>{{ $disactive->bu_type }}</td>
                                        <td>{{ GetMoney($disactive->bu_price) }}</td>
                                        <td>{{ $disactive->bu_square }} M</td>
                                        <td>{{ $disactive->bu_gov }}</td>
                                        <td>{{ $disactive->created_at }}</td>
                                        <td>
                                            <a href="{{ url('/admin-panal/ChangeStatus/'.$disactive->id.'/Active') }}">
                                                <i class="fa fa-check fa-2x"></i>
                                            </a>
                                        </td> 
                                    </tr>
                                    @empty
                                        <tr><td colspan="7">{{ __('No Buildings avilable for this user') }}</td></tr>
                                    @endforelse
                                </table>
                                {!! GetPaginate($buDisactive) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@stop

resources/views/admin/users/form.blade.php
{{-- Name --}}
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
    <div class="col-md-6 col-xs-12">
        @php $thevalue = isset($user) ? $user : null; @endphp
        {!! Form::text('name', $thevalue->name, ['class' => $errors->has('name') ? 'form-control is-invalid' : 'form-control', 'required' => 'required']) !!}
        
        @if ($errors->has('name'))
        <span class="invalid-feedback">
             <strong>{{ $errors->first('name') }}</strong>
        </span> 
        @endif
    </div>
</div>

{{-- Data of birth --}}
<div class="form-group row">
    <label for="dob" class="col-md-4 col-form-label text-md-right">{{ __('Date of Birth') }}</label>
    <div class="col-md-6 col-xs-12">
    
        {!! Form::date('dob', $thevalue->dob, ['class'=> $errors->has('dob') ? 'form-control is-invalid' : 'form-control']) !!}

        @if ($errors->has('dob'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('dob') }}</strong>
        </span> 
        @endif
    </div>
</div>

{{--  Username  --}}
<div class="form-group row">
    <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>
    <div class="col-md-6 col-xs-12">
        
        {!! Form::text('username', $thevalue->username, ['class'=>$errors->has('username') ? 'form-control is-invalid' : 'form-control']) !!}
        
        @if ($errors->has('username'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('username') }}</strong>
        </span> 
        @endif
    </div>
</div>

{{--  Email  --}}
<div class="form-group row">
    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

    <div class="col-md-6 col-xs-12">
        {!! Form::email('email', $thevalue->email, ['class'=> $errors->has('email') ? 'form-control is-invalid' : 'form-control']) !!}

        @if ($errors->has('email'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('email') }}</strong>
        </span> 
        @endif
    </div>
</div>

{{-- location --}}
<div class="form-group row">
    <label for="location" class="col-md-4 col-form-label text-md-right">{{ __('Location') }}</label>
    <div class="col-md-6 col-xs-12">

        {!! Form::text('location', $thevalue->location, ['class'=>$errors->has('location') ? 'form-control is-invalid' : 'form-control']) !!} 
        @if($errors->has('location'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('location') }}</strong>
        </span> 
        @endif
    </div>
</div>

@if(!isset($user) && !isset($some) && !isset($admin))
    <div class="form-group row">
        <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

        <div class="col-md-6 col-xs-12">
            
            <input type="password" name="password" class="form-control" required="required" >
            @if($errors->has('password'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('password') }}</strong>
                </span> 
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>
        <div class="col-md-6 col-xs-12">
            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
        </div>
    </div>
@endif
<div class="form-group row">
    <label for="user_image" class="col-md-4 col-form-label text-md-right">{{ __('User Image') }}</label>
    <div class="col-md-6 col-xs-12">
        <input type="file" name="user_image" class="{{ $errors->has('user_image') ? 'form-control is-invalid' : 'form-control' }}" />

        @if ($errors->has('user_image'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('user_image') }}</strong>
        </span> 
        @endif
    </div>
    <div class="row col-md-12 col-md-offset-4">
        <img width="390" style="margin-top: 10px;" src="{{ SetImage($thevalue->user_image, 'users') }}" class="thumbnail"/>
    </div>
    <div class="clearfix"></div>
</div>

resources/views/admin/users/index.blade.php
@extends('admin.layout.master') 
@section('title', 'Users') 
@section('style') 
    {{ Html::style('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}
@stop
 
@section('content')

<section dir="rtl" class="content-header">
    <h1 class="pull-left" dir="ltr">Data Tables<small>advanced tables</small></h1>
    <ol class="breadcrumb">
        <li class="h4"><a href="{{ route('admin-panal') }}">Home</a></li>
        <li class="active h4">Users</li>
    </ol>
</section>

<br><br>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Display all Users</h3>
                </div>

                <div class="box-body">
                    <table id="data" class="table table-bordered table-hover text-center">
                        <thead>
                            <tr><th>{{ __('#') }}</th><th>Name</th><th>MY Buildings</th><th>Email</th><th>DOB</th><th>Location</th><th>Iamge</th><th>Edit</th><th>Delete</th></tr>
                        </thead>

                        <tbody class="text-center" style="font-size: 15px;">
                        </tbody>

                        <tfoot>
                            <tr><th>{{ __('#') }}</th><th>Name</th><th>MY Buildings</th><th>Email</th><th>DOB</th><th>Location</th><th>Iamge</th><th>Edit</th><th>Delete</th></tr>
                        </tfoot>

                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@stop
 
@section('script') 

{{ Html::script('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }} 
{{ Html::script('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}

<script type="text/javascript">
    var lastIdx = null;
    
    $('#data thead th').each( function () {
        
        if($(this).index()  < 6 && $(this).index() != 2 ){
            var classname = $(this).index() == 7  ?  'date' : 'dateslash';
            var title = $(this).html();    
            $(this).html(`<input type="text" class="${classname}" data-value="${$(this).index()}" placeholder=" Search ${title}"/>`);
        }
    });

    var table = $('#data').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url('/admin-panal/users/data') }}',
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'mybus', name: 'mybus'},
            {data: 'email', name: 'email'},
            {data: 'dob', name: 'dob'},
            {data: 'location', name: 'location'},
            {data: 'user_image', name: 'user_image'},
            {data: 'edit', name: 'edit'},
            {data: 'delete', name: 'delete'}
        ],
        
        "stateSave": false,
        "responsive": true,
        "order": [[0, 'ASC']],
        "pagingType": "full_numbers",
        
        aLengthMenu: [[10, 50, 100, 200, -1], [10, 50, 100, 200, "All"]],
        iDisplayLength: 10,
        fixedHeader: true,

        "oTableTools": {
            "aButtons": [
                {
                    "sExtends": "csv",
                    "sButtonText": "Excel File",
                    "sCharSet": "utf16le"
                },
                {
                    "sExtends": "copy",
                    "sButtonText": "Copy Information",
                },
                {
                    "sExtends": "print",
                    "sButtonText": "Print",
                    "mColumns": "visible",
                }
            ],
            "sSwfPath": "{{ Request::root() }}/admin/cus/copy_csv_xls_pdf.swf"
        },
        
        "dom": '<"pull-left text-left" T><"pullright" i><"clearfix"><"pull-right text-right col-lg-6" f > <"pull-left text-left" l><"clearfix">rt<"pull-right text-right col-lg-6" pi > <"pull-left text-left" l><"clearfix"> '
        ,initComplete: function (){
            var r = $('#data tfoot tr');
            r.find('th').each(function(){
                $(this).css('padding', 5);
            });
            $('#data thead').append(r);
            $('#search_0').css('text-align', 'center');
        }
    });
    table.columns().eq(0).each(function(colIdx) {
        $('input', table.column(colIdx).header()).on('keyup change', function() {
            table
            .column(colIdx)
            .search(this.value)
            .draw();
        });
    });
    
    table.columns().eq(0).each(function(colIdx) {
        $('select', table.column(colIdx).header()).on('change', function() {
            table
            .column(colIdx)
            .search(this.value)
            .draw();
        });

        $('select', table.column(colIdx).header()).on('click', function(e) {
            e.stopPropagation();
        });
    });
    
    $('#data tbody').on( 'mouseover', 'td', function (){
        var colIdx = table.cell(this).index().column;
        if ( colIdx !== lastIdx ) {
            $( table.cells().nodes() ).removeClass( 'highlight' );
            $( table.column( colIdx ).nodes() ).addClass( 'highlight' );
        }
    })
    .on( 'mouseleave', function () {
        $( table.cells().nodes() ).removeClass( 'highlight' );
    });

</script>
@stop